import pytest
# Replace 'ds' with the actual module name generated by your parallelized engine
import py_data_structures as ds  


# 1. Environment Fixture to hold static sample data keys/values
class CuckooContext:
    def __init__(self):
        self.keys = [
            "a", "z", "c", "d", "e", "g", "s", "f", "h", "k", 
            "j", "i", "b", "l", "t", "p", "n", "o", "r", "q", 
            "ab", "ac", "ad", "ae", "aq", "aa", "ag", "ah", "ai", "aj"
        ]
        self.values = [
            1, 4, 6, 5, 9, 12, 22, 43, 47, 41, 
            50, 40, 20, 8, 7, 15, 13, 19, 21, 90, 
            104, 102, 103, 201, 105, 203, 254, 291, 221, 210
        ]


@pytest.fixture
def env():
    """Provides the exact key-value mapping context from the C++ test suite."""
    return CuckooContext()


# 2. Translated Test Blocks
def test_cuckoo_map(env):
    # Instantiate your custom CuckooHashMap reflection-bound object
    # Assuming your constructor parameters are mapped as (max_load_factor, min_load_factor)
    ch = ds.CuckooHashMap(str, int, 0.3, 0.2)
    
    for i in range(30):
        ch.insert(env.keys[i], env.values[i])
        
    assert ch.size() == 30
    
    for i in range(20):
        # Natively triggers your C++26 reflected operator[] -> __getitem__
        assert ch[env.keys[i]] == env.values[i]
        ch.erase(env.keys[i])
        
    assert ch.size() == 10

    ch.insert("string", 155)

    # Reassignment, not insertion. Triggers your C++26 reflected operator[] -> __setitem__
    ch["string"] = 144
    assert ch["string"] == 144


def test_cuckoo_set(env):
    # Instantiate your custom CuckooHashSet reflection-bound object
    cs = ds.CuckooHashSet(str, 0.3, 0.2)
    
    for i in range(30):
        cs.insert(env.keys[i])
        
    for i in range(30):
        # Triggers your bound container membership lookup or verification function
        assert cs.contains(env.keys[i]) is True
        
    for i in range(25):
        cs.erase(env.keys[i])
        
    cs.clear()
    assert cs.empty() is True
    
    for i in range(10, 15):
        cs.insert(env.keys[i])
